version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: fhir-demo-source
    container_name: fhir-demo-source
    environment:
      - ISC_CPF_MERGE_FILE=/irisdev/app/merge.cpf
    command: 
      --check-caps false
    ports: 
      - 1972
      - 52001:52773
      - 53773
    volumes:
      - ./:/irisdev/app
      - ./init.db/:/docker-entrypoint-initdb.d/
      - ./jdbc:/jdbc

  lorah:
    build: 
      context: fhir_server/.
      dockerfile: Dockerfile
    image: fhir_server
    restart: always
    hostname: lorah
    container_name: lorah
    command: 
      --check-caps false
    ports: 
      - 1973
      - 52002:52773
      - 53774
    volumes:
      - ./:/irisdev/app
      - ./jdbc:/jdbc

  oscar:
    image: fhir_server
    restart: always
    hostname: oscar
    container_name: oscar
    command: 
      --check-caps false
    ports: 
      - 1973
      - 52003:52773
      - 53774
    volumes:
      - ./:/irisdev/app
      - ./jdbc:/jdbc

  notebook:
    build: 
      context: notebook
      dockerfile: dockerfile
    ports:
      - "8889:8888"
    volumes:
      - ./notebook/Notebooks:/Notebooks
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/Notebooks"
  postgres:
    container_name: fhirdemo-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgreSQL:/docker-entrypoint-initdb.d/
      - ./volumes/postgreSQL:/var/lib/postgresql/data
    ports:
      - 52004:5432
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 30s
        timeout: 30s
        retries: 3
